services:
  rpgc-telegram-bot:
    container_name: rpgc-telegram-bot
    image: rpgc-telegram-bot
    build:
      context: ./telegramBot
      args:
        ugid: ${UGID}
    env_file: ./telegramBot/.env
    volumes:
      - ./data:/home/rpgc/data
    networks:
      - rpgc-network
  rpgc-discord-bot:
    container_name: rpgc-discord-bot
    image: rpgc-discord-bot
    build:
      context: ./discordBot
      args:
        ugid: ${UGID}
    env_file: ./discordBot/.env
    volumes:
      - ./data:/home/rpgc/data
    networks:
      - rpgc-network
  rpgc-api:
    container_name: rpgc-api
    image: rpgc-api
    build:
      context: ./api
      args:
        ugid: ${UGID}
    env_file: ./api/.env
    volumes:
      - ./data:/home/rpgc/data
    networks:
      - rpgc-network
  rpgc-tools:
    container_name: rpgc-tools
    image: rpgc-tools
    build:
      context: ./tools
      args:
        ugid: ${UGID}
    stdin_open: true
    tty: true
    volumes:
      - ./data/db:/home/rpgc/db
    networks:
      - rpgc-network
networks:
  rpgc-network:
    name: rpgc-network