services:
  rpgc-bot:
    container_name: rpgc-bot
    image: rpgc-bot
    build:
      context: ./bot
      args:
        ugid: ${UGID}
    env_file: ./bot/.env
    volumes:
      - ./data:/home/rpgc/data
    networks:
      - rpgc-network
networks:
  rpgc-network:
    name: rpgc-network